### ISSUE TITLE
Need of open source friendly license.

### ISSUE THREAD

**Issue by elfmimi** [OpenNuvoton/NUC123BSP#3]
While it is named "OpenNuvoton", it lacks a license that is friendly and compatible with open source activity.

It should be granted to copy and modify at lease this single file.
 NUC123BSP/Library/Device/Nuvoton/NUC123/Include/NUC123.h 
Or preferably all of the headers in this directory.
 NUC123BSP/Library/Device/Nuvoton/NUC123/Include
Or even the entire NUC123 CMSIS directory.

Currently it just states "All rights reserved".
I want this change to be applied to BSPs of all other products aswell. ex. NUC126.

cf.  SLA0044 "Ultimate Liberty" License
https://www.st.com/content/ccc/resource/legal/legal_agreement/license_agreement/group0/59/57/63/12/cf/a6/47/65/SLA0044/files/SLA0044.txt/jcr:content/translations/en.SLA0044.txt
https://www.st.com/content/ccc/resource/legal/legal_agreement/license_agreement/group0/87/0c/3d/ad/0a/ba/44/26/DM00216740/files/DM00216740.pdf/jcr:content/translations/en.DM00216740.pdf

**Comment by GitWellBack** [comment]
I would very much like to see this change as well.

I've had to re-engineer my entire codebase from chip documentation just to avoid using any of the non-friendly header files from your repository. This work added an extra 3.5 weeks to a project and would require the same work to be repeated for any other MCU in future, without an update to your licensing. 

Unfortunately this would likely mean that I would not choose to use your silicon for future projects, which is a shame as they are quite elegant.

Thank-you for your consideration of this issue.

**Comment by wschang0** [comment]
Hi,

We do know your concern about the license of our BSP.
Basically, it is welcome to use them on Nuvoton products.
We are working hard to come out an official license agreement for this.
I think it will be friendly and could be able to apply to all Nuvoton MCU BSPs.

Regards,
WS

**Comment by elfmimi** [comment]
Seems no update yet. I'm periodically checking on this.

**Comment by elfmimi** [comment]
Please, we really need this to be solved.

**Comment by elfmimi** [comment]
I failed to check for updates for few months. 
And today, I realized Nuvoton's BSPs including those for NUC123 and NUC126 are now available under the Apache-2.0 license!
Thank! Thank a lot! I don't know how to thank you enough.
@wschang0 and Nuvoton staff members
